const replacements = [
  ["Tecnologia", "Tecnología"],
  ["tecnologia", "tecnología"],
  ["estrategica", "estratégica"],
  ["satelites", "satélites"],
  ["electrica", "eléctrica"],
  ["bioingenieria", "bioingeniería"],
  ["Opinion", "Opinión"],
  ["opinion", "opinión"],
  ["Analisis", "Análisis"],
  ["analisis", "análisis"],
  ["Mas", "Más"],
  ["mas", "más"],
  ["Senales", "Señales"],
  ["senales", "señales"],
  ["Senal", "Señal"],
  ["senal", "señal"],
  ["Contrasena", "Contraseña"],
  ["contrasena", "contraseña"],
  ["Revision", "Revisión"],
  ["revision", "revisión"],
  ["autenticacion", "autenticación"],
  ["Autenticacion", "Autenticación"],
  ["informacion", "información"],
  ["Informacion", "Información"],
  ["Quienes", "Quiénes"],
  ["quienes", "quiénes"],
  ["Articulo", "Artículo"],
  ["articulo", "artículo"],
  ["Articulos", "Artículos"],
  ["articulos", "artículos"],
  ["Generacion", "Generación"],
  ["generacion", "generación"],
  ["proximos", "próximos"],
  ["Proximos", "Próximos"],
  ["politica", "política"],
  ["Politica", "Política"],
  ["cientifica", "científica"],
  ["cientifico", "científico"],
  ["clinico", "clínico"],
  ["genica", "génica"],
  ["orbita", "órbita"],
  ["boletin", "boletín"],
  ["sintetica", "sintética"],
  ["energetica", "energética"],
  ["fotónico", "fotónico"],
  ["fotonico", "fotónico"],
  ["aun", "aún"],
  ["Tambien", "También"],
  ["tambien", "también"]
] as const;

export function restoreSpanishText(value: string) {
  return replacements.reduce((text, [search, replacement]) => text.replaceAll(search, replacement), value);
}
